substitutions:
  device_name: geothermie
  friendly_name: Geothermie
  device_description: Contrôle de zones HVAC multi-zones pour géothermie

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  includes:
    - zone_states.h

external_components:
  - source: github://jlacasse/openZoningPannel
    ref: main
    refresh: 0s
    components: [zone_states]

esp8266:
  board: nodemcuv2

logger:

captive_portal:
