substitutions:
  device_name: geothermie
  friendly_name: Geothermie
  device_description: Contrôle de zones HVAC multi-zones pour géothermie

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  description: ${device_description}

esp8266:
  board: nodemcuv2

logger:

captive_portal:
