select:
- platform: template
  name: "Geo_Output_mode"
  id: Geothermie_mode_select
  optimistic: true
  restore_value: true
  options:
    - Arrêt              # index 0
    - Fan1               # index 1
    - Clim Stage 1       # index 2
    - Clim Stage 2       # index 3
    - Chauffage Stage 1  # index 4
    - Chauffage Stage 2  # index 5
    - Purge Chauffage    # index 6 - Fan only, OB OFF (last was heating)
    - Purge Clim         # index 7 - Fan only, OB ON (last was cooling)
  initial_option: Arrêt
  # NOTE: on_value lambda removed — mode application is handled by
  # OpenZoningController::apply_mode_() in the C++ component (Phase 0D).
  # The select entity is synced by the component via make_call().set_index().
